# Generated by Django 3.0.3 on 2021-12-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('taxa_id', models.IntegerField()),
                ('clade', models.CharField(max_length=1)),
                ('genus', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PfamDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('domain_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('sequence', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('length', models.IntegerField()),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.Sequencing')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.PfamDescriptions')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domains', to='proteinData.Protein')),
            ],
        ),
    ]
