# Generated by Django 3.0.3 on 2021-12-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PfamDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('pfam_desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('sequence', models.CharField(blank=True, max_length=40000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('org_taxa_id', models.IntegerField()),
                ('org_clade', models.CharField(max_length=1)),
                ('org_genus', models.CharField(max_length=256)),
                ('org_species', models.CharField(max_length=256)),
                ('domain_id', models.CharField(max_length=256)),
                ('domain_desc', models.CharField(max_length=256)),
                ('domain_start_coord', models.IntegerField()),
                ('domain_end_coord', models.IntegerField()),
                ('protein_length', models.IntegerField()),
                ('pfam_desc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.PfamDescriptions')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.Sequencing')),
            ],
        ),
    ]
