# Generated by Django 3.0.3 on 2021-12-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='taxa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinData.Organism'),
        ),
    ]
