# Generated by Django 3.0.3 on 2021-12-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfamdescriptions',
            old_name='pfam_id',
            new_name='domain_id',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='id',
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
