# Generated by Django 3.0.3 on 2021-12-28 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proteinData.Sequencing'),
        ),
    ]
