# Generated by Django 3.0.3 on 2021-12-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0003_auto_20211228_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencing',
            name='sequence',
            field=models.TextField(blank=True, default=''),
        ),
    ]
