# Generated by Django 3.0.3 on 2021-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0004_auto_20211228_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencing',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
