# Generated by Django 3.0.3 on 2021-12-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0004_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Testing',
        ),
    ]
