# Generated by Django 3.0.3 on 2021-12-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0005_auto_20211229_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
