# Generated by Django 3.0.3 on 2021-12-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinData', '0006_delete_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('domain_id', models.CharField(max_length=256)),
                ('domain_desc', models.CharField(max_length=256)),
                ('domain_start_coord', models.IntegerField()),
                ('domain_end_coord', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=10)),
                ('org_taxa_id', models.IntegerField()),
                ('org_clade', models.CharField(max_length=1)),
                ('org_genus', models.CharField(max_length=256)),
                ('org_species', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domain_desc',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domain_end_coord',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domain_id',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='domain_start_coord',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='org_clade',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='org_genus',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='org_species',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='org_taxa_id',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='pfam_desc',
        ),
    ]
